language: node_js
node_js:
- "12"
env:
  global:
  - NPM_TAG=latest
  - RELEASE_VERSION="0.1.0-prerelease.$(date +'%Y%m%d%H%M%S')"
addons:
  chrome: stable
cache:
  directories:
  - node_modules

before_install:
# Symlink closure library
- ln -s $(npm root)/google-closure-library ../closure-library

before_script:
  - export DISPLAY=:99.0
  - tests/scripts/setup_linux_env.sh
  - sleep 2
script:
  - i18n/sync_translations.sh
  - npm test
before_deploy:
- >
  if [ -z "$BEFORE_DEPLOY_RAN" ]; then
    npm --no-git-tag-version version $RELEASE_VERSION
    if [[ "$TRAVIS_BRANCH" == hotfix/* ]]; then export NPM_TAG=hotfix; fi # double brackets are important for matching the wildcard
    git config --global user.email $(git log --pretty=format:"%ae" -n1)
    git config --global user.name $(git log --pretty=format:"%an" -n1)
    export BEFORE_DEPLOY_RAN=true
  fi
deploy:
- provider: npm
  on:
    branch:
    - master
    - develop
    - hotfix/*
  skip_cleanup: true
  email: $NPM_EMAIL
  api_key: $NPM_TOKEN
  tag: $NPM_TAG
- provider: script
  on:
    all_branches: true
    condition: $TRAVIS_EVENT_TYPE != cron && ! $TRAVIS_BRANCH =~ ^greenkeeper/
    tags: false # Don't push tags to gh-pages
  skip_cleanup: true
  script: npm run --silent deploy -- -x -r https://${GH_TOKEN}@github.com/${TRAVIS_REPO_SLUG}.git
